#!/usr/bin/env sh
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
  CREATE USER $POSTGRES_DB_USER WITH PASSWORD '$POSTGRES_DB_PASSWORD' CREATEDB;
  CREATE DATABASE $POSTGRES_DB_NAME WITH OWNER $POSTGRES_DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_NAME TO $POSTGRES_DB_USER;
EOSQL
