[project]
name = "test-ugc"
version = "0.1.0"
description ="Test UGC project" 
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django~=5.2.7",
    "faker~=37.11.0",
    "psycopg2-binary~=2.9.11",
]
