# Generated by Django 5.2.7 on 2025-10-19 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст ответа')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответов',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='заголовок')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='опрос'),
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.survey', verbose_name='опрос')),
                ('user', models.ForeignKey(help_text='Пользователь, завершивший опрос', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='опрашиваемый')),
            ],
            options={
                'verbose_name': 'результат опроса',
                'verbose_name_plural': 'результаты опросов',
            },
        ),
        migrations.CreateModel(
            name='SurveyResultChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.choice', verbose_name='ответ')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyresult', verbose_name='результат')),
            ],
            options={
                'verbose_name': 'ответ в результате опросов',
                'verbose_name_plural': 'ответы в результате опроса',
            },
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['order', 'created_at'], name='surveys_cho_order_4fe25e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order', 'created_at'], name='surveys_que_order_c41c99_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresult',
            index=models.Index(fields=['user', 'survey'], name='surveys_sur_user_id_523fed_idx'),
        ),
    ]
